config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#index'
  resources:homes
  resources:albums do
  resources:comments
  end

  resources:images
  
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
    belongs_to :user
    has_many_attached :images,dependent: :destroy
    has_many :comments
    validates :album_name,presence:true
    validates :album_description,presence:true
    scope :sorted,lambda {order(album_name: :desc)}

    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :album
end

app/models/image.rb
class Image < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many:albums
end

app/controllers/album_controller.rb
class AlbumController < ApplicationController
    def index

        @album = current_user.albums
       end
     
       def show
        @album =Album.find(params[:id])
        @album.images.attached?
        @comenter=@album.comments


       end
     
       def new
         @album = Album.new
       end
     
       def create
         @album = current_user.albums.new(album_params)
         if @album.save
           redirect_to root_path
         else
           render('new')
         end
       end
     
       def edit   
         @album = Album.find(params[:id])  
       end
       def update 
         @album = Album.find(params[:id])
         if @album.update(album_params)
           redirect_to root_path
         else
           render('edit')
         end
       end 
        
       def delete
     
       end
       def destroy 
         
           @album = Album.find(params[:id])
           @album.destroy
           redirect_to root_path
        
           
       end
       private    
       def album_params
         params.require(:album).permit(:album_name, :album_description, images: [])
       end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
        def index
            @album = current_user.albums.sorted
        end
     
       def show
            @album = Album.find(params[:id])
            @album.images.attached?
            @comenter = @album.comments
       end
     
       def new
         @album = Album.new
       end
     
       def create
         @album = current_user.albums.new(album_params)
         if @album.save
           redirect_to root_path
         else
           render('new')
         end
       end
     
       def edit   
         @album = Album.find(params[:id])  
       end
       def update 
         @album = Album.find(params[:id])
         if @album.update(album_params)
           redirect_to album_path
         else
           render('edit')
         end
       end 
        
       def delete
     
       end
       def destroy 
         
           @album = Album.find(params[:id])
           @album.destroy
           redirect_to root_path
        
           
       end
       private    
       def album_params
         params.require(:album).permit(:album_name, :album_description, images: [])
       end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
    def index
        
    end

    def create
        @album = Album.find(params[:album_id])
        @comment = @album.comments.create( params.permit(:body))
        redirect_to album_path(@album)
     end
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def index
        
    end

    def create
        @album = Album.find(params[:album_id])
        @comment = @album.comments.create( params.permit(:body))
        redirect_to album_path(@album)
     end
    
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!
  
  def index
       @album = current_user.albums.sorted
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
    def index
        @album = current_user.albums
    
    end
    def destroy
        image = ActiveStorage::Blob.find_signed(params[:id])
        image.purge
        redirect_to root_path
    end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/album/show.html.erb
<%= link_to "back",root_path,:class=>:"btn btn-primary"%> 
<table class="table">
  <tr>
    <th><%=@album.album_name%></th>
    <th>
      <%=@album.album_description%>
    </th>
  </tr>
</table>
<h1>images:</h1>
<% @album.images.each do |image| %>
  <span style="width:140px; height:200px;">
    <%= image_tag(image)%>
    <%= link_to 'Remove', image_path(image.signed_id), method: :delete, data: { confirm: 'Are you sure?' } %>
    <%#= button_to 'Delete', image_path, :method => 'delete', data:{ confirm: "Are you sure?" } %>
  <span>
<% end %>

<h2>Comments</h2>
  <% @comenter.each do |comment| %>
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
<% end %>


  <h2>Add a comment:</h2>
  <%= form_with model:@comment,url:album_comment_index_url(@album.id) do |form| %>
    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>

app/views/albums/delete.html.erb
<h1>Home#delete</h1>
<p>Find me in app/views/home/delete.html.erb</p>

app/views/albums/edit.html.erb
<h1>Home#edit</h1>
<p>Find me in app/views/home/edit.html.erb</p>
 <%= render "layouts/form", album: @album %>

app/views/albums/new.html.erb
<h1>Home page</h1>

 <%= render "layouts/form", album:@album%>

app/views/albums/show.html.erb
<%= link_to "back",root_path,:class=>:"btn btn-primary"%> 
<br>
<table class="table">
  <tr>
    <th><%=@album.album_name%></th>
    <th>
      <%=@album.album_description%>
    </th>
  </tr>
</table>
<h1>images:</h1>
<% @album.images.each do |image| %>
  <span style="width:140px; height:200px;">
    <%= image_tag(image)%>
    <%= link_to 'Remove', image_path(image.signed_id), method: :delete, data: { confirm: 'Are you sure?' } %>
    <%#= button_to 'Delete', image_path, :method => 'delete', data:{ confirm: "Are you sure?" } %>
  <span>
<% end %>

<h2>Comments</h2>
  <% @comenter.each do |comment| %>
  <p>
    <strong>comments:</strong>
    <%= comment.body %>
  </p>
<% end %>


  <h2>Add a comment:</h2>
  <%= form_with model:@comment,url:album_comments_path(@album.id) do |form| %>
    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>

app/views/home/index.html.erb
<table class="table">
   <tr> 
      <td colspan="4"; class="btn btn-success btn-block"><a href="<%=new_album_path%>" >add album</a></td>
   </tr>
    <tr>
        <td>album_name</td>
        <td>album_description</td>
        <td>action</td> 
    </tr>
        <% @album.each do|i| %>
        <tr><td><%=i.album_name%></td>
        <td><%=i.album_description%></td>
        <td> 

         <%= link_to "delete",album_path(i.id),:class=>:"btn btn-danger",method: :delete,data: { confirm: "Are you sure?" }%>
   
        <a href="<%=edit_album_path(i.id)%>" class="btn btn-info">edit</a>
        <a href="<%=album_path(i.id)%>" class="btn btn-info">show album</a>

        </td>
  </tr>
  <%end%>
  </table>

app/views/homes/index.html.erb
<table class="table">
   <tr> 
      <td  class="btn btn-success btn-block"><a href="<%=new_album_path%>" >add album</a></td>
   </tr>
    <tr>
        <th>album_name</th>
        <th>album_description</th>
        <th>action</th> 
    </tr>
        <% @album.each do|i| %>
        <tr><td><%=i.album_name%></td>
        <td><%=i.album_description%></td>
        <td> 

         <%= link_to "delete",album_path(i.id),:class=>:"btn btn-danger",method: :delete,data: { confirm: "Are you sure?" }%>
   
        <a href="<%=edit_album_path(i.id)%>" class="btn btn-info">edit</a>
        <a href="<%=album_path(i.id)%>" class="btn btn-info">show album</a>

        </td>
  </tr>
  <%end%>
  </table>

app/views/layouts/_footer.html.erb
</div>

app/views/layouts/_form.html.erb
<%if action_name=='edit'%>
<%url=album_path%>
<% else %>
<%url = albums_path%>
<%end%>


<%= form_with model:album, url:url do |form| %>

<div class="form-group form-control-lg">
    <%= form.label :album_name %><br>
    <%= form.text_field :album_name,:class =>"form-control" %>
    <% @album.errors.full_messages_for(:album_name).each do |message| %>
    <div class="alert-danger"><%=message%></div>
    <%end%>
  </div>

    <div class="form-group form-control-lg">
      <%= form.label :album_description%><br>
      <%= form.text_field :album_description,:class =>"form-control"%>
      <% @album.errors.full_messages_for(:album_description).each do |message| %>
          <div class="alert-danger">
            <%=message%>
        </div>
      <%end%>
    </div>

    <div class="form-group form-control-lg">
      <% @album.images.each do |image| %>
            <%if image.present?%>
              <%= image_tag(image)%>
            <%end%>
        <%end%>
    </div>

    <div>
    <%= form.label :images%><br>
    <%= form.file_field :images,accept: "images/*", multiple: true,direct_upload: true%>
     <% @album.errors.full_messages_for(:images).each do |message| %>
    <div class="alert-danger"><%=message%></div>
    <%end%>
  </div>
  <br>
  <div class="form-group">
    <%= form.submit :class =>"btn btn-primary"%>
  </div>
<% end %>
</div>

app/views/layouts/_header.html.erb
<div class="container">
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Album app</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="/">Home</a></li>
      <li><a href="#">Page 1</a></li>
      <li><a href="#">Page 2</a></li>
      <li><a href="#">Page 3</a></li>
      
      <li><% if !user_signed_in?%>
      <a href="//users/sign_in">sign_in</a></li>
      <%end%>
      <li><% if current_user.present?%>
      <%= link_to "signout", destroy_user_session_path,method: :delete,data: { confirm: "Are you sure?" }%>sign out</a></li>
      <%end%>
    </ul>
  </div>
</nav>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Appalbum</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  </head>

  <body>
  <%= render partial:"layouts/header"%>
   <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
    <%= yield %>
   <%= render partial:"layouts/footer"%>
  </body>
</html>